sequenceDiagram
    Title: Add New Notes in SPA
    participant browser
    participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    Note right of browser: Browser sends the new note as JSON
    activate server
    Note left of server: Server executes code to save new Note
    server-->>browser: 201 Response
    deactivate server
