sequenceDiagram
    Title: Add New Notes in SPA
    participant browser
    participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server
    server-->>browser: 201 Response
    deactivate server
